Repository akshitagit/JAVA, pull requests merged in 2020-09, with the labels that each got.

#27 Create QuickSort.java
  Searching & Sorting/QuickSort.java
Labels: Hacktoberfest, hacktoberfest2020

#26 Create SelectionSort.java
  Searching & Sorting/SelectionSort.java
Labels: Hacktoberfest, algorithm, hacktoberfest2020

#33 Create Anagrams.java
  Strings/Anagrams.java
Labels: Hacktoberfest, good first issue, hacktoberfest2020

#37 Create HeapSort.java
  Searching & Sorting/HeapSort.java
Labels: algorithm, good first issue, hacktoberfest2020
